export const FETCH_PROJECTS = 'FETCH_POSTS'
export const NEW_PROJECT = 'NEW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECTS_REQUEST_STARTED = 'PROJECT_REQUEST_STARTED'
export const PROJECTS_REQUEST_SUCCESS = 'PROJECT_REQUEST_SUCCESS'


